blank_issues_enabled: false
contact_links:
  - name: â“ ShowTrackr Q&A Discussions
    url: https://github.com/Exonymos/ShowTrackr-Web/discussions/categories/q-a
    about: Have a question about setting up or using ShowTrackr? Ask the community first!
  - name: ğŸ’¡ ShowTrackr Ideas & Feature Discussions
    url: https://github.com/Exonymos/ShowTrackr-Web/discussions/categories/ideas
    about: Share and discuss new feature ideas with the community.
  - name: ğŸ’¬ ShowTrackr General Chat
    url: https://github.com/Exonymos/ShowTrackr-Web/discussions/categories/general
    about: For other general discussions related to ShowTrackr.
